### ISSUE TITLE
Greyed out Keystone

### ISSUE THREAD

**Issue by Skidadle** [cogwerkz/Bagnon_Garbage#2]
Hi, it seems that keystones and mining pick is set to garbage.
![bagnon garbage](https://user-images.githubusercontent.com/31952271/30579604-ab9a8b5c-9d19-11e7-8f32-8e008a548993.png)

**Comment by amber1019** [comment]
This is still an issue as of 01/05/2018.

Author -- Any plans on fixing this?

**Comment by goldpaw** [comment]
They're not grayed out for me. 

![screenshot from 2018-01-29 03-18-12](https://user-images.githubusercontent.com/6476535/35490899-137ddd82-04a3-11e8-846c-64ff7e00e373.png)
